Use systemctl instead of rc* and chkconfig
Signed-off-by: Tim Serong <tserong@suse.com>

diff --git a/scripts/ha-cluster-functions b/scripts/ha-cluster-functions
--- a/scripts/ha-cluster-functions
+++ b/scripts/ha-cluster-functions
@@ -82,20 +82,20 @@ invoke()
 
 start_service()
 {
-	status "Enabling $1 service"
+	status "Enabling $1"
 
-	invoke chkconfig $1 on
-	rc$1 status >/dev/null
+	invoke systemctl enable $1
+	systemctl -q is-active $1
 	if [ $? -ne 0 ]; then
-		invoke rc$1 start 2>/dev/null
-		[ $? -ne 0 ] && error "Failed to start $1 service"
+		invoke systemctl start $1 2>/dev/null
+		[ $? -ne 0 ] && error "Failed to start $1"
 	fi
 }
 
-# Determines if a service is chkconfig'd on (not if it's actually running)
+# Determines if a service is enabled (not if it's actually running)
 service_is_on()
 {
-	chkconfig $1 | egrep -q "$1[[:space:]]+on"
+	systemctl is-enabled $1 >/dev/null 2>&1
 }
 
 status()
@@ -188,8 +188,8 @@ wait_for_cluster()
 init_cluster_local()
 {
 	# Caller should check this, but I'm paranoid...
-	rcopenais status >/dev/null
-	[ $rc -ne 7 ] && error "openais service is not stopped!"
+	systemctl -q is-active corosync.service
+	[ $? -eq 0 ] && error "corosync service is running!"
 
 	# reset password, but only if it's not already set
 	local ps=$(passwd -S hacluster 2>/dev/null | cut -d' ' -f2)
@@ -207,7 +207,7 @@ EOF
 	# evil, but necessary
 	invoke rm -f /var/lib/heartbeat/crm/* /var/lib/pacemaker/cib/*
 
-	start_service hawk
+	start_service hawk.service
 	status "  HA Web Konsole is now running, to see cluster status go to:"
 	[ -n "$IP_ADDRESS" ] && status "    https://$IP_ADDRESS:7630/" \
 		|| status "    https://SERVER:7630/"
@@ -216,7 +216,7 @@ EOF
 	[ -n "$pass_msg" ] && \
 		warn "You should change the hacluster password to something more secure!"
 
-	start_service openais
+	start_service pacemaker.service
 	wait_for_cluster
 }
 
@@ -384,7 +384,7 @@ check_prereqs()
 		warned=1
 	fi
 
-	if ! service_is_on ntp ; then
+	if ! service_is_on ntp.service ; then
 		warn "NTP is not configured to start at system boot."
 		warned=1
 	fi
diff --git a/scripts/ha-cluster-remove b/scripts/ha-cluster-remove
--- a/scripts/ha-cluster-remove
+++ b/scripts/ha-cluster-remove
@@ -63,10 +63,8 @@ remove_ssh()
 {
 	[ -n "$SEED_HOST" ] || error "No existing IP/hostname specified (use -c option)"
 
-	start_service sshd
-
-	#check whether the openais service has been started on local node
-	invoke rcopenais status >/dev/null
+	#check whether corosync has been started on local node
+	systemctl -q is-active corosync.service
 	local rc=$?
 	[ $rc -ne 0 ] && error "Cluster is not active - can't execute removing action"
 
@@ -141,9 +139,8 @@ remove_cluster()
 	if [ $HOST_STATUS -ne 0 ]; then
 		status "Stopping the openais service"
 	
-		#invoke ssh root@$SEED_HOST "rcopenais stop && rm /etc/corosync/corosync.conf " \
-		invoke ssh root@$HOST "rcopenais stop" \
-      		|| error "stop the service rcopenais on $SEED_HOST failed"
+		invoke ssh root@$HOST "systemctl stop corosync" \
+			|| error "stop the service corosync on $SEED_HOST failed"
 
 		#delete the configure file from the node $SEED_HOST
 		invoke ssh root@$HOST "rm -f $SYSCONFIG_SBD $CSYNC2_CFG \
