Support non-RSA SSH keys when joining node to existing cluster (bnc#878080)
Signed-off-by: Tim Serong <tserong@suse.com>

diff --git a/scripts/ha-cluster-join b/scripts/ha-cluster-join
--- a/scripts/ha-cluster-join
+++ b/scripts/ha-cluster-join
@@ -56,21 +56,48 @@ join_ssh()
 {
 	[ -n "$SEED_HOST" ] || error "No existing IP/hostname specified (use -c option)"
 
+	local -i got_keys=0
+
 	start_service sshd.service
 
 	invoke mkdir -m 700 -p /root/.ssh
 
-	if [ -f /root/.ssh/id_rsa ]; then
-		confirm \
-			'/root/.ssh/id_rsa already exists - overwrite?' || return
-	fi
+	local tmp_dir=/tmp/ha-cluster-ssh.$$
+	invoke mkdir -p $tmp_dir || error "Can't create temporary directory $tmp_dir"
+	invoke rm -f $tmp_dir/*
 
 	status "Retrieving SSH keys from $SEED_HOST"
 	invoke scp -oStrictHostKeyChecking=no \
-		root@$SEED_HOST:'/root/.ssh/id_rsa*' /root/.ssh/ \
+		root@$SEED_HOST:'/root/.ssh/id_*' $tmp_dir/ \
 		|| error "Can't retrieve SSH keys from $SEED_HOST"
-	grep -q -s "$(cat /root/.ssh/id_rsa.pub)" /root/.ssh/authorized_keys \
-		|| append /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
+
+	# This supports all SSH key types, for the case where ha-cluster-init
+	# wasn't used to set up the seed node, and the user has manually
+	# created, for example, DSA keys (bnc#878080)
+	for key in id_rsa id_dsa id_ecdsa id_ed25519 ; do
+		[ -f $tmp_dir/$key ] || continue
+		if [ -f /root/.ssh/$key ]; then
+			confirm \
+				"/root/.ssh/$key already exists - overwrite?" || continue
+		fi
+		invoke mv $tmp_dir/$key* /root/.ssh/
+		grep -q -s "$(cat /root/.ssh/$key.pub)" /root/.ssh/authorized_keys \
+			|| append /root/.ssh/$key.pub /root/.ssh/authorized_keys
+		let got_keys=$got_keys+1
+	done
+
+	invoke rm -r $tmp_dir
+
+	[ $got_keys -eq 0 ] && status "No new SSH keys installed"
+	[ $got_keys -eq 1 ] && status "One new SSH key installed"
+	[ $got_keys -gt 1 ] && status "$got_keys new SSH keys installed"
+
+	# This makes sure the seed host has its own SSH keys in its own
+	# authorized_keys file (again, to help with the case where the
+	# user has done manual initial setup without the assistance of
+	# ha-cluster-init).
+	invoke ssh root@$SEED_HOST ha-cluster-init ssh_remote \
+		|| error "Can't invoke ha-cluster-init ssh_remote on $SEED_HOST"
 }
 
 join_csync2()
