Rename from sleha-* to ha-cluster-*
Signed-off-by: Tim Serong <tserong@suse.com>

diff --git a/scripts/ha-cluster-join b/scripts/ha-cluster-join
--- a/scripts/ha-cluster-join
+++ b/scripts/ha-cluster-join
@@ -24,7 +24,7 @@
 # Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
 #
 
-. /usr/lib/sleha-functions
+. /usr/lib/ha-cluster-functions
 
 declare SEED_HOST
 
@@ -88,9 +88,9 @@ join_csync2()
 	#[ -n "$hosts_line" ] || error "No valid entry for $(hostname) in /etc/hosts - csync2 can't work"
 
 	# If we *were* updating /etc/hosts, the next line would have "\"$hosts_line\"" as
-	# the last arg (but this requires re-enabling this functionality in sleha-init)
-	invoke ssh root@$SEED_HOST sleha-init csync2_remote $(hostname) \
-		|| error "Can't invoke sleha-init csync2_remote on $SEED_HOST"
+	# the last arg (but this requires re-enabling this functionality in ha-cluster-init)
+	invoke ssh root@$SEED_HOST ha-cluster-init csync2_remote $(hostname) \
+		|| error "Can't invoke ha-cluster-init csync2_remote on $SEED_HOST"
 
 	# This is necessary if syncing /etc/hosts (to ensure everyone's got the
 	# same list of hosts)
@@ -134,7 +134,7 @@ join_ssh_merge()
 
 	[ -z "$host_args" ] && error "Unable to extract host list from $CSYNC2_CFG"
 
-	local tmp_dir=/tmp/sleha-pssh.$$
+	local tmp_dir=/tmp/ha-cluster-pssh.$$
 	invoke mkdir -p $tmp_dir || error "Can't create temporary directory $tmp_dir"
 	invoke rm -f $tmp_dir/*
 	# The act of using pssh to connect to every host (without strict host key
