Automatically update /etc/hosts to ensure name resolution works for csync

diff --git a/scripts/hae-functions b/scripts/hae-functions
--- a/scripts/hae-functions
+++ b/scripts/hae-functions
@@ -24,7 +24,7 @@
 # Inc., 59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
 #
 
-declare -r INVOCATION="$0 $*"
+declare -r INVOCATION=$(printf '%q ' "$0" "$@")
 declare -r LOG_FILE=/var/log/hae-bootstrap.log
 declare -r CSYNC2_KEY=/etc/csync2/key_hagroup
 declare -r CSYNC2_CFG=/etc/csync2/csync2.cfg
@@ -235,6 +235,52 @@ append()
 {
 	log "+ cat $1 >> $2"
 	cat $1 >> $2
+}
+
+# Call with $1 == hostname, $2 == new line to add to /etc/hosts
+# if there's no entry already for hostname.  Make sure you quote
+# the new line so it comes in as one arg!
+etc_hosts_add_one()
+{
+	local newhost=$1
+	local newline=$2
+
+	# If host doesn't already exist in /etc/hosts, add it
+	if ! egrep -q -s \
+		"^[[:digit:]]+.*\\b${newhost}\\b" \
+		/etc/hosts
+	then
+		local tmp_conf=/etc/hosts.$$
+		cp /etc/hosts $tmp_conf
+		echo "$newline" >> $tmp_conf
+		install_tmp $tmp_conf /etc/hosts
+	else
+		log ": Not updating /etc/hosts - remote host $newhost already exists"
+	fi
+}
+
+# Returns success if there's an entry for the current node
+# (regardless of whether it's mapped to localhost or a real IP)
+etc_hosts_has_me()
+{
+	egrep -q "^[[:digit:]]+.*\\b$(hostname)\\b" /etc/hosts
+}
+
+# Prints the line from /etc/hosts for the current node (unless
+# it maps to localhost), in which case you get nothing)
+etc_hosts_get_me()
+{
+	egrep "^[[:digit:]]+.*\\b$(hostname)\\b" /etc/hosts | grep -v '^127'
+}
+
+# Adds current node to /etc/hosts if it doesn't already exist
+etc_hosts_add_me()
+{
+	etc_hosts_has_me && return
+
+	status "Adding entry for $(hostname) to /etc/hosts"
+	[ -n "$IP_ADDRESS" ] || error "Unable to determine this node's IP address"
+	etc_hosts_add_one $(hostname) "$IP_ADDRESS $(hostname)"
 }
 
 _onexit()
diff --git a/scripts/hae-init b/scripts/hae-init
--- a/scripts/hae-init
+++ b/scripts/hae-init
@@ -86,6 +86,10 @@ init_ssh()
 
 init_csync2()
 {
+	# Need hostname resolution to work
+	etc_hosts_add_me
+	[ -n "$(etc_hosts_get_me)" ] || error "No valid entry for $(hostname) in /etc/hosts - csync2 can't work"
+
 	status "Configuring csync2"
 
 	if [ -f "$CSYNC2_KEY" ] || \
@@ -113,6 +117,7 @@ group ha_group
 	include /etc/ctdb/nodes;
 	include /etc/drbd.d;
 	include /etc/ha.d/ldirectord.cf;
+	include /etc/hosts;
 	include /etc/lvm/lvm.conf;
 	include /etc/multipath.conf;
 	include /etc/samba/smb.conf;
@@ -141,13 +146,22 @@ END
 # So we have this function which is called by hae-join to add the new
 # remote node to csync2 config on some existing node.  It is intentionally
 # not documented in hae-init's user-visible usage information.
+# Note that this function also adds the remote node to /etc/hosts (we
+# need local name resolution to work).
 init_csync2_remote()
 {
 	local newhost=$1
+	local newline="$2"
 	local thishost=$(hostname)
 	[ -n "$newhost" ] || error "Hostname not specified"
 
 	BE_QUIET=true
+
+	if [ -n "$newline" ]; then
+		etc_hosts_add_one $newhost "$newline"
+	else
+		log ": Not updating /etc/hosts - remote host line not specified"
+	fi
 
 	# If host doesn't already exist in csync2 config, add it
 	if ! egrep -q -s \
@@ -161,7 +175,7 @@ init_csync2_remote()
 		install_tmp $tmp_conf $CSYNC2_CFG
 		invoke csync2 -c $CSYNC2_CFG
 	else
-		log ": Nothing to do - remote host $newhost already exists"
+		log ": Not updating $CSYNC2_CFG - remote host $newhost already exists"
 	fi
 }
 
@@ -517,23 +531,25 @@ done
 
 shift $(($OPTIND - 1))
 
+stage=$1 ; shift
+
 # vgfs stage requires running cluster, everything else requires inactive cluster,
 # except ssh (which doesn't care) and csync2_remote (which mustn't care, just in
 # case this breaks hae-join on another node).
 rcopenais status >/dev/null
 rc=$?
-if [ "$1" == "vgfs" ]; then
+if [ "$stage" == "vgfs" ]; then
 	[ $rc -ne 0 ] && error "Cluster is inactive  - can't run vgfs stage"
-elif [ "$1" != "ssh" -a "$1" != "csync2_remote" ]; then
+elif [ "$stage" != "ssh" -a "$stage" != "csync2_remote" ]; then
 	[ $rc -eq 0 ] && error "Cluster is currently active - can't run"
 	[ $rc -ne 7 ] && error "rcopenais status returned unexpected status ($rc)"
 fi
 
-case $1 in
+case $stage in
 ssh|csync2|csync2_remote|corosync|storage|sbd|cluster|vgfs)
 	log_start
 	# $2 == nasty hack to pick up IP arg to csync2_remote
-	init_$1 $2
+	init_$stage "$@"
 	;;
 "")
 	log_start
diff --git a/scripts/hae-join b/scripts/hae-join
--- a/scripts/hae-join
+++ b/scripts/hae-join
@@ -34,6 +34,7 @@ Usage: $0 [options] [stage]
 
 Options:
     -c          IP address or hostname of existing cluster node
+    -i <if>     Default to IP address on interface 'if' instead of eth0
     -h          Display this usage information
     -q          Be quiet (don't describe what's happening, just do it)
     -y          Answer "yes" to all prompts (use with care)
@@ -73,10 +74,20 @@ join_csync2()
 {
 	[ -n "$SEED_HOST" ] || error "No existing IP/hostname specified (use -c option)"
 
+	etc_hosts_add_me
+	local hosts_line=$(etc_hosts_get_me)
+	[ -n "$hosts_line" ] || error "No valid entry for $(hostname) in /etc/hosts - csync2 can't work"
+
 	status "Configuring csync2"
 
-	invoke ssh root@$SEED_HOST hae-init csync2_remote $(hostname) \
+	invoke ssh root@$SEED_HOST hae-init csync2_remote $(hostname) "\"$hosts_line\"" \
 		|| error "Can't invoke hae-init csync2_remote on $SEED_HOST"
+
+	# This is necessary for hostname resolution to work (*sigh*)
+	local tmp_conf=/etc/hosts.$$
+	invoke scp root@$SEED_HOST:/etc/hosts $tmp_conf \
+		|| error "Can't retrieve /etc/hosts from $SEED_HOST"
+	install_tmp $tmp_conf /etc/hosts
 
 	invoke scp root@$SEED_HOST:'/etc/csync2/{csync2.cfg,key_hagroup}' \
 		/etc/csync2 \
@@ -118,9 +129,10 @@ join_cluster()
 
 #------------------------------------------------------------------------------
 
-while getopts 'c:hqy' o; do
+while getopts 'c:i:hqy' o; do
 	case $o in
 	c) SEED_HOST=$OPTARG;;
+	i) NET_IF=$OPTARG;;
 	h) usage;;
 	q) BE_QUIET=true;;
 	y) YES_TO_ALL=true;;
