Add cluster stage to hae-join

diff --git a/scripts/hae-join b/scripts/hae-join
--- a/scripts/hae-join
+++ b/scripts/hae-join
@@ -41,6 +41,7 @@ Options:
 Stage can be one of:
     ssh         Obtain SSH keys from existing cluster node (requires -c <ip>)
     csync2      Configure csync2 (requires -c <ip>)
+    cluster     Start the cluster on this node
 
 If stage is not specified, each stage will be invoked in sequence.
 END
@@ -90,6 +91,35 @@ join_csync2()
 	invoke ssh root@$SEED_HOST 'csync2 -mr / ; csync2 -xv'
 }
 
+join_cluster()
+{
+	rcopenais status >/dev/null
+	rc=$?
+	[ $rc -eq 0 ] && error "Cluster is currently active - can't run"
+	[ $rc -ne 7 ] && error "rcopenais status returned unexpected status ($rc)"
+
+	# reset password, but only if it's not already set
+	local ps=$(passwd -S hacluster 2>/dev/null | cut -d' ' -f2)
+	local pass_msg
+	if [ "$ps" != "PS" ]; then
+		log ': Resetting password of hacluster user'
+		echo "linux" | passwd --stdin hacluster > /dev/null
+		pass_msg=", password 'linux'"
+	fi
+
+	# evil, but necessary
+	invoke rm -f /var/lib/heartbeat/crm/*
+
+	start_service hawk
+	status "  HA Web Konsole is now running, to see cluster status go to:"
+	[ -n "$IP_ADDRESS" ] && status "    https://$IP_ADDRESS:7630/" \
+		|| status "    https://SERVER:7630/"
+	status "  Log in with username 'hacluster'${pass_msg}"
+
+	start_service openais
+	wait_for_cluster
+}
+
 while getopts 'c:hqy' o; do
 	case $o in
 	c) SEED_HOST=$OPTARG;;
@@ -102,7 +132,7 @@ done
 shift $(($OPTIND - 1))
 
 case $1 in
-ssh)
+ssh|csync2|cluster)
 	log_start
 	join_$1
 	;;
@@ -110,6 +140,7 @@ ssh)
 	log_start
 	join_ssh
 	join_csync2
+	join_cluster
 	;;
 *)	echo -e "Invalid stage ($1)\n"
 	usage
