Warn if $(hostname) unresolvable; don't auto-generate /etc/hosts

diff --git a/scripts/hae-init b/scripts/hae-init
--- a/scripts/hae-init
+++ b/scripts/hae-init
@@ -97,11 +97,11 @@ init_ssh()
 
 init_csync2()
 {
-	# Need hostname resolution to work
-	etc_hosts_add_me
-	[ -n "$(etc_hosts_get_me)" ] || error "No valid entry for $(hostname) in /etc/hosts - csync2 can't work"
-
 	status "Configuring csync2"
+
+	# Not automatically updating /etc/hosts - risky in the general case.
+	#etc_hosts_add_me
+	#[ -n "$(etc_hosts_get_me)" ] || error "No valid entry for $(hostname) in /etc/hosts - csync2 can't work"
 
 	if [ -f "$CSYNC2_KEY" ] || \
 		grep -v -q -s '^[[:space:]]*\(#.*\)*$' $CSYNC2_CFG
@@ -128,7 +128,6 @@ group ha_group
 	include /etc/ctdb/nodes;
 	include /etc/drbd.d;
 	include /etc/ha.d/ldirectord.cf;
-	include /etc/hosts;
 	include /etc/lvm/lvm.conf;
 	include /etc/multipath.conf;
 	include /etc/samba/smb.conf;
@@ -157,22 +156,21 @@ END
 # So we have this function which is called by hae-join to add the new
 # remote node to csync2 config on some existing node.  It is intentionally
 # not documented in hae-init's user-visible usage information.
-# Note that this function also adds the remote node to /etc/hosts (we
-# need local name resolution to work).
 init_csync2_remote()
 {
 	local newhost=$1
-	local newline="$2"
+	#local newline="$2"
 	local thishost=$(hostname)
 	[ -n "$newhost" ] || error "Hostname not specified"
 
 	BE_QUIET=true
 
-	if [ -n "$newline" ]; then
-		etc_hosts_add_one $newhost "$newline"
-	else
-		log ": Not updating /etc/hosts - remote host line not specified"
-	fi
+	# Not automatically updating /etc/hosts - risky in the general case.
+	#if [ -n "$newline" ]; then
+	#	etc_hosts_add_one $newhost "$newline"
+	#else
+	#	log ": Not updating /etc/hosts - remote host line not specified"
+	#fi
 
 	# If host doesn't already exist in csync2 config, add it
 	if ! egrep -q -s \
@@ -609,6 +607,13 @@ elif [ "$stage" != "ssh" -a "$stage" != "csync2_remote" ]; then
 	[ $rc -ne 7 ] && error "rcopenais status returned unexpected status ($rc)"
 fi
 
+# Need hostname resolution to work (but don't block csync2_remote)
+if ! my_hostname_resolves && [ "$stage" != "csync2_remote" ]; then
+	warn "Hostname '$(hostname)' is unresolvable - csync2 won't work."
+	warn "You should add an entry to /etc/hosts or configure DNS."
+	confirm 'Do you want to continue anyway?' || exit
+fi
+
 case $TEMPLATE in
 ocfs2)	;;
 "")	;;
@@ -618,7 +623,8 @@ esac
 case $stage in
 ssh|csync2|csync2_remote|corosync|storage|sbd|cluster|vgfs)
 	log_start
-	# $2 == nasty hack to pick up IP arg to csync2_remote
+	# $2 == nasty hack to pick up IP arg to csync2_remote (not strictly
+	# necessary currently, as we're not auto-updating /etc/hosts)
 	init_$stage "$@"
 	;;
 "")
diff --git a/scripts/hae-join b/scripts/hae-join
--- a/scripts/hae-join
+++ b/scripts/hae-join
@@ -75,20 +75,24 @@ join_csync2()
 {
 	[ -n "$SEED_HOST" ] || error "No existing IP/hostname specified (use -c option)"
 
-	etc_hosts_add_me
-	local hosts_line=$(etc_hosts_get_me)
-	[ -n "$hosts_line" ] || error "No valid entry for $(hostname) in /etc/hosts - csync2 can't work"
-
 	status "Configuring csync2"
 
-	invoke ssh root@$SEED_HOST hae-init csync2_remote $(hostname) "\"$hosts_line\"" \
+	# Not automatically updating /etc/hosts - risky in the general case.
+	#etc_hosts_add_me
+	#local hosts_line=$(etc_hosts_get_me)
+	#[ -n "$hosts_line" ] || error "No valid entry for $(hostname) in /etc/hosts - csync2 can't work"
+
+	# If we *were* updating /etc/hosts, the next line would have "\"$hosts_line\"" as
+	# the last arg (but this requires re-enabling this functionality in hae-init)
+	invoke ssh root@$SEED_HOST hae-init csync2_remote $(hostname) \
 		|| error "Can't invoke hae-init csync2_remote on $SEED_HOST"
 
-	# This is necessary for hostname resolution to work (*sigh*)
-	local tmp_conf=/etc/hosts.$$
-	invoke scp root@$SEED_HOST:/etc/hosts $tmp_conf \
-		|| error "Can't retrieve /etc/hosts from $SEED_HOST"
-	install_tmp $tmp_conf /etc/hosts
+	# This is necessary if syncing /etc/hosts (to ensure everyone's got the
+	# same list of hosts)
+	#local tmp_conf=/etc/hosts.$$
+	#invoke scp root@$SEED_HOST:/etc/hosts $tmp_conf \
+	#	|| error "Can't retrieve /etc/hosts from $SEED_HOST"
+	#install_tmp $tmp_conf /etc/hosts
 
 	invoke scp root@$SEED_HOST:'/etc/csync2/{csync2.cfg,key_hagroup}' \
 		/etc/csync2 \
@@ -147,6 +151,13 @@ if [ "$1" != "ssh" ]; then
 	rc=$?
 	[ $rc -eq 0 ] && error "Cluster is currently active - can't run"
 	[ $rc -ne 7 ] && error "rcopenais status returned unexpected status ($rc)"
+fi
+
+# Need hostname resolution to work
+if ! my_hostname_resolves ; then
+	warn "Hostname '$(hostname)' is unresolvable - csync2 won't work."
+	warn "You should add an entry to /etc/hosts or configure DNS."
+	confirm 'Do you want to continue anyway?' || return
 fi
 
 case $1 in
