Don't replace all cluster properties when enabling STONITH

diff --git a/scripts/hae-init b/scripts/hae-init
--- a/scripts/hae-init
+++ b/scripts/hae-init
@@ -419,12 +419,14 @@ END
 	local sbd_device=$([ -f /etc/sysconfig/sbd ] && \
 		. /etc/sysconfig/sbd ; echo $SBD_DEVICE)
 	if [ -n "$sbd_device" ]; then
-		local tmp_conf=/tmp/crm.$$
-		cat > $tmp_conf <<END
-property stonith-enabled="true"
-primitive stonith-sbd stonith:external/sbd params sbd_device="$sbd_device"
-END
-		crm_configure_load update $tmp_conf
+		# Can't do crm configure load update here with only
+		# stonith-enabled, or it wipes out then entire
+		# cib-bootstrap-options section
+		# TODO: find out if this is a bug in the crm shell
+		invoke crm configure primitive stonith-sbd stonith:external/sbd params sbd_device="$sbd_device" \
+			|| error "Can't create stonith-sbd primitive"
+		invoke crm configure property stonith-enabled="true" \
+			|| error "Can't enable STONITH"
 	fi
 }
 
