Bug: Reset password of correct user
Make sure to set the password of hacluster, not root.
Also, log if passwd returns != 0.

diff --git a/scripts/sleha-functions b/scripts/sleha-functions
--- a/scripts/sleha-functions
+++ b/scripts/sleha-functions
@@ -196,10 +196,11 @@ init_cluster_local()
 	local pass_msg
 	if [ "$ps" != "PS" ]; then
 		log ': Resetting password of hacluster user'
-		passwd > /dev/null 2>&1 <<EOF
+		passwd hacluster > /dev/null 2>&1 <<EOF
 linux
 linux
 EOF
+		[ $? -ne 0 ] && log ": Failed to reset password of hacluster user"
 		pass_msg=", password 'linux'"
 	fi
 
